const ADD_USER = "user:ADD_USER";
const GET_ALL_USERS = "user:GET_ALL_USERS";
const DELETE_USER = "user:DELETE_USER";
const DEACT_ACCOUNT = "user:DEACT_ACCOUNT";

const ADD_ADMIN = "admin:ADD_ADMIN";

const ADD_WALLET = "wallet:ADD_WALLET";
const GET_ALL_WALLETS = "wallet:GET_ALL_WALLETS";
const DElETE_WALLET = "wallet:DELETE_WALLET";
const UPDATE_WALLET = "wallet:UPDATE_WALLET";

const ADD_CONVERSION = "conversion:ADD_CONVERSION";
const GET_ALL_CONVERSIONS = "conversion:GET_ALL_CONVERSIONS";
const DELETE_CONVERSION = "conversion:DELETE_CONVERSION";
const UPDATE_CONVERSION = "conversion:UPDATE_CONVERSION";

module.exports = {
    ADD_ADMIN,
    ADD_USER,
    GET_ALL_USERS,
    DELETE_USER,
    DEACT_ACCOUNT,
    ADD_WALLET,
    GET_ALL_WALLETS,
    DElETE_WALLET,
    UPDATE_WALLET,
    ADD_CONVERSION,
    GET_ALL_CONVERSIONS,
    DELETE_CONVERSION,
    UPDATE_CONVERSION
}